/**
 * Clan invites, carried by an ordinary direct message.
 *
 * ── Why a message and not a table ────────────────────────────────────
 * A group is already invite-only and the invite is already the join
 * code — "unguessable, and rotatable by the owner if it leaks", per
 * groups_schema.sql. So inviting someone is telling them the code, and
 * a DM between accepted friends is exactly the private channel for it.
 * No new table, no migration, and nothing to keep in step.
 *
 * The messages table has no `kind` column, so the marker lives in the
 * body. That is a deliberate trade: the format has to be strict enough
 * to parse and readable enough that a client which does not parse it —
 * an older build, a future export, a push notification preview — still
 * shows something that makes sense.
 *
 *   ⚔ Clan invite · code 7QK2P9 · Night Owls
 *
 * The code comes BEFORE the name so the name can contain anything at
 * all, including the separator, without breaking the parse.
 *
 * A false positive costs nothing: someone typing this by hand has
 * written a real invite, and a bogus code fails cleanly at the server
 * with "that code doesn't match a group".
 *
 * Pure. No React, no network.
 */

/** The sentinel. Distinctive enough not to appear by accident. */
export const INVITE_PREFIX = '⚔ Clan invite · code ';

/**
 * Codes are generated by netlify/functions/groups.js. Kept permissive
 * on purpose — this validates the SHAPE so the parser knows where the
 * code ends, and the server remains the only thing that decides whether
 * a code is real.
 */
const CODE = /^[A-Z0-9-]{4,32}$/;

/** The body to send. Returns null when there is nothing to invite to. */
export function formatInvite(group) {
  const code = (group?.inviteCode || '').trim();
  const name = (group?.name || '').trim();
  if (!code || !CODE.test(code)) return null;
  return `${INVITE_PREFIX}${code} · ${name || 'my clan'}`;
}

/**
 * Read an invite back out of a message body.
 * @returns {{code: string, name: string}|null} null for ordinary messages.
 */
export function parseInvite(body) {
  if (typeof body !== 'string') return null;
  const text = body.trim();
  if (!text.startsWith(INVITE_PREFIX)) return null;
  const rest = text.slice(INVITE_PREFIX.length);
  const sep = rest.indexOf(' · ');
  // A code with no name after it is still a usable invite; the name is
  // presentation, the code is the thing that works.
  const code = (sep === -1 ? rest : rest.slice(0, sep)).trim();
  if (!CODE.test(code)) return null;
  const name = sep === -1 ? '' : rest.slice(sep + 3).trim();
  return { code, name };
}

/** True when this body is an invite. */
export const isInvite = body => parseInvite(body) !== null;
