/**
 * CoachNudges — proactive nudges card. Sits above the daily brief
 * inside CoachBriefPanel. Pro-only surface (the panel that owns it
 * is gated already; this component doesn't re-check).
 *
 * Renders up to 3 active nudges (server-generated by the LLM
 * function, or client-side heuristic fallbacks until the function
 * is enabled). Each nudge has Dismiss + (optional) action verbs.
 *
 * Empty state: render nothing — don't take up space when there's
 * no signal. The daily brief carries the user's attention slot.
 */
import { useEffect } from 'react';
import Icon from './Icon';
import { useCoachNudges } from '../hooks/useCoachNudges';

export default function CoachNudges({ S, userId, onCoachAct }) {
  const { nudges, dismiss, act, markSeen } = useCoachNudges(S, userId);

  // Ping seen_at for any server nudges currently rendered (heuristic
  // ones no-op). Single effect rather than per-card so we don't spam
  // PATCH requests on every re-render.
  useEffect(() => {
    nudges.forEach(n => {
      if (n._source === 'server' && !n.seen_at) markSeen(n.id);
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [nudges.map(n => n.id).join(',')]);

  if (!nudges || nudges.length === 0) return null;

  return (
    <div className="coach-nudges">
      <div className="coach-nudges-header">
        <span className="coach-nudges-icon" aria-hidden="true" style={{display:'inline-flex'}}><Icon name="sparkles" size={14} /></span>
        <span className="coach-nudges-title">Patterns worth a look</span>
        <span className="coach-nudges-count">{nudges.length}</span>
      </div>

      <ul className="coach-nudges-list">
        {nudges.map(nudge => (
          <li key={nudge.id} className={`coach-nudge coach-nudge-${nudge._source}`}>
            <div className="coach-nudge-body">
              <p className="coach-nudge-text">{nudge.body}</p>
              {nudge._source === 'heuristic' && (
                <span
                  className="coach-nudge-source"
                  title="Detected on-device. Pro unlocks deeper LLM-generated nudges."
                >Local</span>
              )}
            </div>
            <div className="coach-nudge-actions">
              {Array.isArray(nudge.verbs) && nudge.verbs.map((verb, i) => (
                <button
                  key={i}
                  type="button"
                  className="coach-nudge-verb"
                  onClick={() => {
                    onCoachAct?.(verb);
                    act(nudge.id, verb);
                  }}
                >
                  {verb.label}
                </button>
              ))}
              <button
                type="button"
                className="coach-nudge-dismiss"
                onClick={() => dismiss(nudge.id)}
                aria-label="Dismiss this nudge"
                title="Dismiss"
              ><Icon name="x" size={13} /></button>
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
}
